#ifndef GRAPHICS_8_CONSOLE_DL_H
#define GRAPHICS_8_CONSOLE_DL_H

#include <atari.h>

void graphics_8_console_dl = {
    DL_BLK8,
    DL_LMS(DL_GRAPHICS0), 0xFFFF,  // Header that shows application name and version
    DL_LMS(DL_GRAPHICS8), &framebuffer[0]+320, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8,
    DL_LMS(DL_GRAPHICS8), &framebuffer[0]+0x1000, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8,
    // 5 text lines
    DL_LMS(DL_GRAPHICS0), 0xFFFF, DL_GRAPHICS0, DL_GRAPHICS0, DL_GRAPHICS0, DL_GRAPHICS0,
    DL_JVB, &graphics_8_console_dl
};

#endif // GRAPHICS_8_CONSOLE_DL_H
